// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOmFNARL_igGbqccknDrjAcpoS6n4URNE',
    appId: '1:599076933274:web:9085c28c5796fcf63cd923',
    messagingSenderId: '599076933274',
    projectId: 'chums-top',
    authDomain: 'chums-top.firebaseapp.com',
    storageBucket: 'chums-top.firebasestorage.app',
    measurementId: 'G-5GE2G12565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmrQDYwnQMSSaUksDXL9WJnro65-Y8UYY',
    appId: '1:599076933274:android:16947b348e0fae133cd923',
    messagingSenderId: '599076933274',
    projectId: 'chums-top',
    storageBucket: 'chums-top.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpwTgCYY0gNJvPfERmpYBdSLCbY0aK3Ok',
    appId: '1:599076933274:ios:7613243503733a073cd923',
    messagingSenderId: '599076933274',
    projectId: 'chums-top',
    storageBucket: 'chums-top.firebasestorage.app',
    iosBundleId: 'top.chums.quiz',
  );

}